apiVersion: v1
kind: Service
metadata:
  name: gateway-api-app-service
  namespace: gateway-demo
  labels:
    app: gateway-api-app
spec:
  type: ClusterIP
  selector:
    app: gateway-api-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
